# Generated by Django 5.0.6 on 2024-11-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0004_remove_event_time_event_ttime_alter_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ttime',
            new_name='time',
        ),
    ]
