# Generated by Django 5.0.6 on 2024-11-30 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0007_alter_event_description_alter_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
